### ISSUE TITLE
Cannot find module './mbxtools-view'

### ISSUE THREAD

**Issue by dbrianwalton** [oscarlevin/atom-language-mbx#1]
After a first-time install of Atom on Mac OS, I attempted to install language-pretext package. At the end of the install process, I had an error.

Uncaught Error: Cannot find module './mbxtools-view'
module.js:545

Stack trace:
Error: Cannot find module './mbxtools-view'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/waltondb/.atom/packages/language-pretext/lib/language-pretext.js:7:21)
    at Object.<anonymous> (/Users/waltondb/.atom/packages/language-pretext/lib/language-pretext.js:49:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:267:16)
    at PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:279:25)
    at PackageDetailView.completeInitialization (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:213:18)
    at PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:563:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:659:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:498:32
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by oscarlevin** [comment]
This should be fixed in 0.1.1.  Please try to reinstall and let me know if the problem persists.
